// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL (sem -pooler) é obrigatória em produção: `migrate deploy` usa advisory lock
    // do Postgres pra evitar migração concorrente, e o PgBouncer em transaction mode (que é
    // o que a string pooled do Neon usa) não sustenta esse lock — falha com timeout (P1002).
    // Fallback pra DATABASE_URL só pra manter o dev local funcionando com uma URL só.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
